title: ""
logo: "/images/pfp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <h1>Trevor Foresta</h1>
  <b>About Me</b>
  I am a software engineer from Wilmington, Delaware interested in studying machine learning and distributed systems. Currently I am an undergraduate student at the University of Delaware, pursuing a B.S. in Computer Science with my concentration being in Artificial Intelligence and Robotics, and minoring in Electrical & Computer Engineering.
  <br><br>
  I am seeking any opportunities for an engaging or just a learning experience.

  Feel free to contact me:
  Personal email: trevforesta@gmail.com
  University email: foresta@udel.edu
  <a href="https://www.linkedin.com/in/trevor-foresta/">My LinkedIn profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
