title: Trevor L. Foresta # your name (or website title) here
logo: "/images/pfp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  I am an undergraduate student at the University of Delaware, currently pursuing a B.S. in Computer Science with my concentration in Artificial Intelligence and Robotics, and minoring in Electrical & Computer Engineering.
  <br><br>
  Feel free to contact me through my email at trevforesta@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/trevor-foresta/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
